### ISSUE TITLE
Search API returns only the first 100 results, even with offset

### ISSUE THREAD

**Issue by xathon** [RIPE-NCC/whois#1145]
In my usecase, I want to query for every address range that belongs to a company. If that company is large and has a lot of address ranges, the results will exceed the 100 results that can be displayed in the web UI. It doesn't appear to be possible to get more than the first 100 results, even when using the parameters `rows` and `offset`. The API should be able to return every result that has been found in the database, even if they're not used/shown in the web UI. Alternatively, the output could still be limited to 100, but the offset parameter could be changed so that it is applied to the whole set of found results, and not the first 100 (currently, setting the offset to 100 returns no results).

**Comment by eshryane** [comment]
Hello @xathon the current _full text search_ API is limited to 100 results because it's meant to be used only for the web page (https://apps.db.ripe.net/db-web-ui/fulltextsearch) and most users don't go past the first page. We also have a concern that the current API could be used to query excessively for personal data (because it's possible to make very specific queries, e.g. for names, email addresses, phone numbers etc.).

We are planning to work on an improved, public full text search API next year, which will return more results and balanced with personal data limits.

In the meantime, I suggest you use the Whois Search API with an inverse query on the organisation's org-id to find all top-level resources (referencing the organisation), for example for the RIPE NCC:

`
https://rest.db.ripe.net/search.json?query-string=org-rien1-ripe&inverse-attribute=org&type-filter=aut-num&type-filter=inet6num&type-filter=inetnum&flags=no-referenced&flags=no-irt&source=RIPE
`

**Comment by xathon** [comment]
Appreciate the response! Yeah, that makes sense that this would want to be limited, and I'm looking forward to the new API. Also thanks for the pointer to the other API.
