### ISSUE TITLE
[feature request] whois-api: support PGP auth, please

### ISSUE THREAD

**Issue by TLINDEN** [RIPE-NCC/whois#382]
Currently I have to use the REST APi to download my objects but the mail interface to update them. This is annoying. A little, at least. So it would be great if PGP auth could be implemented. The signature could be a detached signature, which could be put into its own field during POST and PUT.

Tom

**Comment by timbru** [comment]
Hi Tom, good point but before deciding to do this we believe it would be best to discuss the use of API keys (and possibly also PGP keys) in the Database Working Group.

Would you like to raise this on the mailing list yourself? If you are not subscribed, you can do so here:
https://www.ripe.net/mailman/listinfo/db-wg/

I can also proxy your request, but contributors to the working group are always welcome.

**Comment by TLINDEN** [comment]
Of course, I can do that. I'm already on 'members-discuss', so one more list doesn't hurt :)

Tom

**Comment by timbru** [comment]
Ok, great :)

But before you do I should mention that the Database Working Group has a system of numbered work items where suggestions for change should start with a problem statement (and stay clear of implementation), then implementation is discussed, and finally the work can be done:
https://www.ripe.net/manage-ips-and-asns/db/numbered-work-items

However, the process will be discussed in tomorrow's working group meeting here at RIPE 73.

You may want to wait until after the session because this process may change. Of course you can also suggest the change today, but then just be prepared that the working group may want to formally first document the problem statement and then consider this as a solution.

I will close this issue here now, because it will be followed up in the working group.
