### ISSUE TITLE
RIPE API configuration.

### ISSUE THREAD

**Issue by 6footGeek** [RIPE-NCC/whois#445]
Hey RIPE-NCC,
Ive set up a local mirror of the RIPE db, using GRS import. The logs / db confirm that the information is autoupdating at midnight, and the data in the db is what is expected.
The problem Im having is configuring the local WHOIS api on my server so that I can access via a curl command or similar. 

im currently trying : http://xx.xx.xx.xx:1080/ripe/mntner/8.8.8.8.json (and various tweaks of this including replacing 'ripe' with 'test', 'local' etc.
Im getting a 404 not found response from the server.

`<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /ripe/mntner/8.8.8.8.json. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.z-SNAPSHOT</a><hr/>

</body>
</html>
`

I think that this is probably just a configuration issue on my end and am looking for some advice. under the properties file
`
The main / default whois source (RIPE|TEST)
whois.source=LOCAL
whois.additional.sources=

Service ports
port.query=1043
port.api=1080
port.nrtm=0

File system locations
dir.rpsl.export=var${jvmId:}/export
dir.rpsl.export.tmp=var${jvmId:}/export_tmp
dir.rpsl.export.internal=internal
dir.rpsl.export.external=dbase_new
dir.rpsl.export.external.legacy=dbase
dir.update.audit.log=var${jvmId:}/log/audit
dir.grs.import.download=var${jvmId:}/grs
dir.fulltext.index=
fulltext.index.update.interval.msecs=60000

API configuration
api.rest.baseurl=http://rest.db.ripe.net

Comma separated list of GRS sources
grs.sources=RIPE-GRS
grs.sources.dummify=

Comma separated list of IP ranges from which sensitive operations are accessible
ipranges.trusted=127.0.0.1,::1

Comma separated list of IP ranges from which the OSI layer2 load balancer health checks are executed from
ipranges.loadbalancer=127.0.0.1,::1
`
Any advice?

**Comment by eshryane** [comment]
Hi,

the Whois servlet (including the REST API) is configured with the root path "/whois/".

So http://xx.xx.xx.xx:1080/whois/ripe/mntner/8.8.8.8.json should work (i.e., insert /whois/ at the start of the path).

Apologies this is confusing, we don't use "/" as the root path, in order to allow multiple servlets to run together (there's a separate servlet for the RDAP service). Our services are exposed through httpd proxies, so the path is re-mapped. 

I'll update the [Installation Instructions](https://github.com/RIPE-NCC/whois/wiki/Installation-instructions) with this information.

**Comment by 6footGeek** [comment]
Perfect that resolved this issue. Thanks for getting back to me @eshryane .
