### ISSUE TITLE
TEST DB & LIR organization

### ISSUE THREAD

**Issue by sysmat** [RIPE-NCC/whois#787]
- is it possible to create LIR organization by REST API?
- We try https://apps-test.db.ripe.net/ but is not possible to create LIR organization
- Do you have support for openAPI specification for REST API?

Regards

**Comment by eshryane** [comment]
Hello, and firstly apologies for the delay in replying.

(1) No, it's not possible to create a new LIR organisation using the REST API, because we have a business rule restricting `org-type: LIR` to RIPE NCC maintainers. There is a process for becoming a member of the RIPE NCC, our Registry Services department will create the LIR organisation. See https://www.ripe.net/participate/member-support/become-a-member

(2) You *can* create an LIR organisation in our TEST environment, using the TEST-NCC-HM-MNT:

```
organisation:   AUTO-1
org-name:       Test Organisation
country:        NL
org-type:       LIR
address:        Test Address
e-mail: noreply@ripe.net
admin-c:        AA1-TEST
mnt-ref:        TEST-NCC-HM-MNT
mnt-by:         TEST-NCC-HM-MNT
source:         TEST
password: emptypassword
```

The password is visible in the maintainer object in the TEST database:
https://apps-test.db.ripe.net/db-web-ui/lookup?source=test&key=TEST-NCC-HM-MNT&type=mntner

You can also use this maintainer for creating other types of objects. 
See https://www.ripe.net/manage-ips-and-asns/db/ripe-test-database

(3) No, we haven't followed the OpenAPI specification, although it is a good idea. We have used Swagger for our internal APIs.

The Whois REST API is documented in the wiki:
https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API
